[package]
name = "mikkadb-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
anyhow = "1"
bytes = "1"
hex = "0.4.3"
async-trait = "0.1"
socket2 = { version = "0.5", features = ["all"] }
dashmap = "6.0"
parking_lot = "0.12"
pprof = { version = "0.13", features = ["flamegraph", "criterion"], optional = true }

[features]
profiling = ["pprof"]

[lib]
name = "mikkadb_rust"
path = "src/lib.rs"

[[bin]]
name = "mikkadb-rust"
path = "src/main.rs"

